#!/bin/sh

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4
exitstatus=$STATE_OK

while test -n "$1"; do
    case "$1" in
        -w)
            w=$2
            shift
            ;;
        -c)
            c=$2
            shift
            ;;
        -p)
            p=$2
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            print_usage
            exit $STATE_UNKNOWN
            ;;
    esac
    shift
done

free_size=`/usr/local/libexec/nagios/check_disk -u GB -w $w% -c $c% -p $p | awk '{print $7}'`

echo "free memory on $p| free=$free_size"
